### ISSUE TITLE
Easy p-value

### ISSUE THREAD

**Issue by comisora** [wbonat/mcglm#12]
Hello!
Thank you for the good package. Is there a simple way to indicate the significance level or analogues of regression coefficients for fixed and random effects? The medical community is conservative, without simple reports it is difficult to explain the results. Some texts, such as GLMM FAQ, cause a wall of misunderstanding.

**Comment by wbonat** [comment]
Hi,
P-values included in the output of the summary.mcglm function as you requested.
Thanks for your contribution to the mcglm package.

**Comment by wbonat** [comment]
Please, just install the devel version. 
I am including some new functions and probably I will release a new version soon.

**Comment by comisora** [comment]
Thanks for answer!
