### ISSUE TITLE
Runtime based on number of response variables?

### ISSUE THREAD

**Issue by akmorrow13** [wbonat/mcglm#15]
Is there a maximum number of response variables that this is meant for? I tried running with 100, and it did not complete. What is the maximum this has been used for?

**Comment by wbonat** [comment]
Hi,
Actually, it is a really difficult question. It will depend on the type of model you are fitting, on your computer, C and Fortran libraries that you have installed for your R. 
For the standard R installation and personal computer, probably 100 response is too much. 
For 100 response only the covariance structure has 100 + 100*99/2 parameters to be estimated.  
You can use the option verbose = TRUE to show the progress of the fitting to have some idea how it is going on.

**Comment by akmorrow13** [comment]
Thank you for your response @wbonat ! I will try running with verbose.
