### ISSUE TITLE
Random effects 

### ISSUE THREAD

**Issue by JM-RG** [wbonat/mcglm#17]
Hi there,

thank you so much for building up this package. I've managed to run a multivariate mixed model. My model has two outcomes, three fixed predictor (all three categorical factors), one offset and a random intercept (1|ID). I would like to see the random effects (and effect size and p-value if possible) but cannot find the way. I would expect something similar to the output from VarCorr(model) in lme4.  Are they already shown in the summary? is it something related to the Dispersion parameter? sorry if it is a silly or basic question, I'm not a statistician.

Thank you in advance.

**Comment by wbonat** [comment]
Sorry for the long delay to answer. Probably, it is not useful anymore, but anyway.
The mcglm package does not fit random effects models directly as lme4. It fits marginal version of Gaussian mixed models, thus the random effects were already integrated out.
So, there is no random effects to show. It is open question to me if from the marginal model we can obtain the random effects, probably it is possible, but it is not implemented in the mcglm package.
